CREATE SCHEMA IF NOT EXISTS kata;
SET SCHEMA kata;
RUNSCRIPT FROM 'classpath:org/springframework/batch/core/schema-h2.sql';
CREATE TABLE CLIENT (email VARCHAR(100) NOT NULL, password VARCHAR(255) NOT NULL, roles VARCHAR(100) ARRAY, fullName VARCHAR(100) NOT NULL, id BIGINT , PRIMARY KEY (id));
CREATE TABLE ACCOUNT (ASSOCIATEDCLIENT BIGINT NOT NULL, balance NUMERIC(20, 2) NOT NULL, rib VARCHAR(20) NOT NULL, PRIMARY KEY (rib), FOREIGN KEY(ASSOCIATEDCLIENT) REFERENCES CLIENT(id));
CREATE TABLE OPERATION (amount NUMERIC(20, 2) NOT NULL, fromAccount VARCHAR(20), toAccount VARCHAR(20), balance NUMERIC(20, 2) NOT NULL, operationDate TIMESTAMP NOT NULL, FOREIGN KEY(toAccount) REFERENCES ACCOUNT(rib), FOREIGN KEY(fromAccount) REFERENCES ACCOUNT(rib));

INSERT INTO CLIENT VALUES ('ossema.abdennadher@gmail.com','$2a$12$tBEJNIHfUYFC2hqIf3XB7.WBg7XwKRTXTpJIH/w4nwItJRxmdC92i', ARRAY ['ADMIN','CLIENT'], 'Oussema Abdennadher',1);
INSERT INTO CLIENT VALUES ('someFake@email.com','$2a$12$tBEJNIHfUYFC2hqIf3XB7.WBg7XwKRTXTpJIH/w4nwItJRxmdC92i', ARRAY ['CLIENT'], 'Walid Jied',2);
INSERT INTO ACCOUNT VALUES (1, 500 , '00123456789123456789');
INSERT INTO ACCOUNT VALUES (1, 2000 , '00133456789123456789');
INSERT INTO ACCOUNT VALUES (2, 3000 , '00223456789123456789');